module.exports = {
  REACT_APP_ADMIN_QUEUE: process.env.REACT_APP_ADMIN_QUEUE,
  REACT_APP_API_TOKEN: process.env.REACT_APP_API_TOKEN,
  REACT_APP_PASSWORD: process.env.REACT_APP_PASSWORD,
  REACT_APP_STUDENT_QUEUE: process.env.REACT_APP_STUDENT_QUEUE,
  REACT_APP_USERNAME: process.env.REACT_APP_USERNAME,
  REACT_APP_AUTH0_DOMAIN: process.env.NODE_ENV,
  REACT_APP_AUTH0_CLIENT_ID: process.env.NODE_ENV,
  REACT_APP_AUTH0_CLIENT_SECRET: process.env.NODE_ENV,
  REACT_APP_PROD_URL: process.env.NODE_ENV
};
